### PR TITLE
fix timezone issue, display multiple calendar schedules 

### PR DESCRIPTION
**Pull request by hjohns28**
(I deleted the testing file so I could run the program and make sure things were working)

### CODE REVIEW

**Review by maceonthompson — CHANGES_REQUESTED** [review]
Merge this into the branch from #16 for clarity.

**Comment by hjohns28** [comment]
> Merge this into the branch from #16 for clarity.

did that, thank you!

**Review by maceonthompson — APPROVED** [review]
LGTM! Just keep in mind that this will remove SchedulerTest from the displaySchedules (and potentially master when that gets merged). Usually what I do to avoid something like that is to not commit the changes to the file I don't want to edit long term

**Comment by hjohns28** [comment]
> LGTM! Just keep in mind that this will remove SchedulerTest from the displaySchedules (and potentially master when that gets merged). Usually what I do to avoid something like that is to not commit the changes to the file I don't want to edit long term

Thanks for the info, that's good to know! I'll make sure to do that next time.

**Review by kristen-law — APPROVED** [review]
These new changes LGTM. Feel free to merge this into the branch for #16 before addressing the comments in that PR.

**Pull request merged**
