### PR TITLE
Fix prioritize courses

### PR DESCRIPTION
**Pull request by maceonthompson**

### CODE REVIEW

**Review by hjohns28 — APPROVED** [review]
LGTM

**Review by achillesecos — APPROVED** [review]
LGTM

**Comment by maceonthompson** [comment]
I know that it's better practice to create a separate pull request to delete CalendarQuickstart, but since this is everyone who's working on the project (and we've been meaning to do this for a while), and since we're currently collaborating on one branch, it won't create any nasty conflicts & we've all agreed it won't be an issue.

**Review by kristen-law — APPROVED** [review]
LGTM

**Pull request merged**
